spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mall?characterEncoding=utf8&useSSL=false&serverTimezone=GMT
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
  rabbitmq:
    port: 5672
    username: guest
    password: guest
    host: 127.0.0.1
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    #控制台日志配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mappers/*.xml
logging:
  pattern:
#    去掉日志的时间
    console: "{%thread} %-5level %logger{36} -%msg%n"
  path:
# 设置session有效期
server:
#  servlet:
#    session:
#      timeout: 7h
  port: 8882


